// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function combine(classNames) {
  var unwrapedClassNames = Belt_Array.keepMapU(classNames, (function (x) {
          return x;
        }));
  return unwrapedClassNames.join(" ");
}

export {
  combine ,
}
/* No side effect */
