// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(App.make, {}));
}

export {
  
}
/* rootElement Not a pure module */
