// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Classname from "./util/Classname.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as RangeInputModuleCss from "./RangeInput.module.css";

var styles = RangeInputModuleCss;

function RangeInput(props) {
  var onValue = props.onValue;
  var handleChange = function ($$event) {
    $$event.preventDefault();
    Curry._1(onValue, $$event.target.value);
  };
  var min = Belt_Option.map(props.min, (function (prim) {
          return String(prim);
        }));
  var max = Belt_Option.map(props.max, (function (prim) {
          return String(prim);
        }));
  var className = Classname.combine([
        Caml_option.some(styles.input),
        props.className
      ]);
  return JsxRuntime.jsx("input", {
              className: className,
              max: max,
              min: min,
              step: props.step,
              type: "range",
              value: props.value,
              onChange: handleChange
            });
}

var make = RangeInput;

export {
  styles ,
  make ,
}
/* styles Not a pure module */
